site_name: Mrunal Mania Portfolio
site_url: https://mrunalmania.github.io/portfolio/
theme:
  name: material
  language: en
  palette: 
    scheme: default
    primary: light blue
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  features:
    - search.suggest

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - glightbox
  - search


extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/mrunalmania
      name: mrunalmania
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/mrunal_panna
      name: mrunal_panna
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mrunalmania/
      name: Mrunal Mania
    - icon: /fontawesome/regular/envelope
      name: send me an email
      link: mailto:mmania1@asu.edu
  generator: false
  
copyright: Copyright &copy; 2024 Mrunal Ashwinbhai Mania

repo_url: https://github.com/mrunalmania/Pytorch-Learning
repo_name: Portfolio


